Add search
gorden73/java-filmorate pull request #10
Opened 2022-06-09 20:48 UTC by MaxiTrue

Добавлен новый метод getFilmsBySearch в интерфейс FilmStorage, объявил в классах которые имплементируют этот интерфейс. Добавлен новый метод в контроллер FilmController, для получения фильмов по подстроке. Входящие параметры query - строка поиска, by - поле по которому ищем.

2022-06-10 05:36 UTC, kal-an commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/IncorrectParameterException.java
> +public class IncorrectParameterException extends Exception {
Да, это отлично что свой класс написал. Я также сначала сделал, но потом убрал. В своем коде тоже могу тогда задействовать, после merge твоего PR

2022-06-10 05:36 UTC, kal-an commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (queryResult.isBlank() || queryResult.length() < 2) {
Проверку параметров запроса GET нужно проверять в контроллере, и при необходимости выбрасывать исключение там. А еще лучше формировать сообщение включая туда название параметра, а не целого класса – именно это пойдет пользователю в ответ.

2022-06-10 05:36 UTC, kal-an commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            @RequestParam(value = "query") String query,
если не указано значение по умолчанию, то  нужно указать required = true. На мой взгляд

2022-06-10 05:36 UTC, kal-an commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            @RequestParam(value = "by", defaultValue = "title", required = false) String by)
required = false не является обязательным если ты указал значение по умолчанию

2022-06-10 05:36 UTC, kal-an commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +                " GROUP BY f.film_id, f.name, f.description, f.release_date, f.duration, f.mpa" +
Запрос будет работать даже если указать
GROUP BY f.film_id

2022-06-10 05:36 UTC, kal-an commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +                " ORDER BY amount_likes;";
Наверное нужно добавить тип сортировки, в ТЗ не указано в какую сторону, но можно предположить что в сторону убывания.

2022-06-10 05:36 UTC, kal-an commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if(!byResult.equals("title")){
здесь тоже самое, как я описал чуть выше

2022-06-10 07:51 UTC, gorden73 requested changes
Поиск работает, но есть некоторые замечания/рекомендации/наблюдения.

2022-06-10 07:51 UTC, gorden73 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            @RequestParam(value = "query") String query,
А ещё было бы неплохо сделать пагинацию.

2022-06-10 08:09 UTC, gorden73 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (queryResult.isBlank() || queryResult.length() < 2) {
А при добавлении логирования (как сейчас у тебя) будет виден класс, в котором ты применил его. И, кажется, достаточно сообщения при логировании, сам класс указывать не нужно.

2022-06-12 09:47 UTC, MaxiTrue commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        StringBuilder str = new StringBuilder();
исправил

2022-06-12 09:47 UTC, MaxiTrue commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +                " WHERE REPLACE (LOWER (name), ' ', '') LIKE '%" + query + "%'" +
по вопросу обсудили, пока адекватного решения вопроса не нашёл, пока так

2022-06-15 19:44 UTC, gorden73 approved these changes

2022-06-15 19:45 UTC, gorden73 approved these changes

2022-06-15 19:46 UTC, gorden73 approved these changes

2022-06-15 19:47 UTC, merged