add-most-populars
gorden73/java-filmorate pull request #13
Opened 2022-06-11 15:25 UTC by Gidrosliv

2022-06-11 18:21 UTC, mishaprihlop reviewed
В целом можно поправить тип year и sql запрос

2022-06-11 18:21 UTC, mishaprihlop commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +
Здесь возможно забыта скобка

2022-06-11 18:21 UTC, mishaprihlop commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +                                        @PathVariable("year") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
В качестве года мне кажется можно использовать переменную Integer, и в дальнейшем сравнивать с датой фильма через LocalDate.getYear()

2022-06-11 18:21 UTC, mishaprihlop commented on src/main/java/ru/yandex/practicum/filmorate/dao/LikesDao.java
> +    private static final String SQL_POPULARN_FILM = "SELECT f.film_id, f.duration, f.NAME, f.DESCRIPTION, f.MPA, f.RELEASE_DATE, f.name, COUNT(l.LIKES_ID), g.name " +
В select я бы оставил только поля из таблицы films

2022-06-11 18:21 UTC, mishaprihlop commented on src/main/java/ru/yandex/practicum/filmorate/dao/LikesDao.java
> +            "WHERE g.genre_id = ?  AND f.RELEASE_DATE = ? " +
Здесь возможно не стоит сравнивать с датой так учитываются месяцы и дни, и возможно при одинаковом годе из за них равенство не выполнится, можно получить список с требуемыми жанрами, а затем из даты получать год через LocalDate.getYear() и сравнивать

2022-06-11 18:21 UTC, mishaprihlop commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +                .filter(z -> z.getReleaseDate() == year)
Здесь аналогично сравнивать через localDate.getYear(), а параметр year задать как Int

2022-06-12 20:52 UTC, gorden73 requested changes
Запрос в целом работает верно, кроме одного момента(описал в комментарии). Ну и есть кое-какие замечания. Надо поправить.

2022-06-12 20:52 UTC, gorden73 commented on src/main/java/ru/yandex/practicum/filmorate/dao/LikesDao.java
> +            "GROUP BY f.film_id, g.name " +
При проверке запроса через постман, у меня вылезла ошибка bad sql, требовала добавить release_date в GROUP BY.

2022-06-12 20:52 UTC, gorden73 commented on src/main/java/ru/yandex/practicum/filmorate/dao/LikesDao.java
> +            "ORDER BY COUNT(l.LIKES_ID) DESC " +
При проверке запроса через постман, у меня указан limit = 2(фильмов всего два с одинаковыми жанрамиб годы выхода одинаковые, разные дни месяца), при таком значении фильмы выводятся от более позднего (6 день месяца) к более раннему (5 день месяца). Если limit=1 при остальных неизменных условиях, то выводится только ранний фильм (5 день месяца). Я считаю, что так не должно быть, должен выводиться более ранний фильм (6 день месяца).

2022-06-13 19:55 UTC, gorden73 reviewed
Не исправлены некоторые замечания. Перепроверь рациональность добавления параметра genreId в запрос, при условии genreId == null.

2022-06-13 19:55 UTC, gorden73 commented on src/main/java/ru/yandex/practicum/filmorate/dao/LikesDao.java
> +                    (rs, rowNum) -> makeFilm(rs), genreId, limit);
Если у тебя genreId == null, для чего ты этот null передаешь параметром в запрос?

2022-06-13 19:55 UTC, gorden73 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
Ты не добавил описанные выше проверки.

2022-06-15 06:02 UTC, gorden73 approved these changes

2022-06-15 06:03 UTC, gorden73 approved these changes

2022-06-15 17:35 UTC, merged