Filmorate frame
gorden73/java-filmorate pull request #3
Opened 2022-04-20 07:23 UTC by gorden73

2022-04-21 06:00 UTC, kukolev requested changes

2022-04-21 06:00 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
Не выполнено требование ТЗ: Нет тестов на валидацию Film и User. Необходимо добавить тесты.

2022-04-23 03:48 UTC, gorden73 commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
Исправлено.

2022-04-23 03:48 UTC, gorden73 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    Map<Integer, Film> films = new HashMap<>();
Исправлено.

2022-04-23 03:48 UTC, gorden73 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film.getId() != null) {
Исправлено.

2022-04-23 03:49 UTC, gorden73 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public void update(@RequestBody Film film) {
Исправлено.

2022-04-23 03:49 UTC, gorden73 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        if (user.getId() != null) {
Исправлено.

2022-04-23 03:49 UTC, gorden73 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        if (user.getId() == null) {
Исправлено.

2022-04-23 03:49 UTC, gorden73 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    Map<Integer, User> users = new HashMap<>();
Исправлено.

2022-04-23 03:49 UTC, gorden73 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
Исправлено.

2022-04-23 03:49 UTC, gorden73 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
Исправлено.

2022-04-24 11:05 UTC, merged